spring.application.name=auth-service

server.port=8084
# Database connection settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# Auth0 settings
auth0.audience=${AUTH0_AUDIENCE:https://snippetApi}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_URI:https://dev-wto1l4yz3ktfmwub.us.auth0.com/}
# Auth0 Management API Configuration (M2M for fetching user details)
auth0.domain=${AUTH0_DOMAIN:dev-wto1l4yz3ktfmwub.us.auth0.com}
auth0.management.client-id=${AUTH0_M2M_CLIENT_ID:2RnGdbbAgeGrG7Q1bH3urxi27lpCVvQA}
auth0.management.client-secret=${AUTH0_M2M_CLIENT_SECRET:RzclaSOgkhPECC849r7cH85DqlKjwb37nl3st1_0e-DQ8IVdEOsyBiTBl_00-_ve}
auth0.management.audience=${AUTH0_MANAGEMENT_AUDIENCE:https://dev-wto1l4yz3ktfmwub.us.auth0.com/api/v2/}
